### ISSUE TITLE
下载后运行就报错了【please help me】

### ISSUE THREAD

**Issue by lishizx** [ssthouse/organization-chart#2]
下载后直接运行出现bug
-------胖猪---------
【has a bug in running when once run 】 as ：
![image](https://user-images.githubusercontent.com/33240357/49351680-91e32800-f6ef-11e8-8d01-e825c779d58f.png)

**Comment by ssthouse** [comment]
@lishizx 
查了一下, 感觉可能是webpack 打包出的问题, 我在ubuntu和mac上没有这个问题:
https://github.com/d3/d3-selection/issues/185
我可能先得找一台windows重现一下 :confused:

**Comment by ssthouse** [comment]
@lishizx 你可以尝试先修改 `package.json` 里面 D3的版本号试试

**Comment by lishizx** [comment]
> @lishizx你可以尝试先修改`package.json`里面D3的版本号试试

Mr God I soulution this 问题了！ 版本换成了v5.7.0即可运行。very 感谢您的指点，令我对人生突然升起了希望！赞美您嘞！
