### ISSUE TITLE
> 给第二级一行分别增加随机色

### ISSUE THREAD

**Issue by ssthouse** [ssthouse/organization-chart#4]

**Comment by WangLei802** [comment]
![image](https://user-images.githubusercontent.com/39754107/53783428-800e5c80-3f4c-11e9-93d5-2927cd2d9707.png)

**Comment by WangLei802** [comment]
如上图  我需要给他这一行  一个随机色

**Comment by ssthouse** [comment]
是希望把蓝色换成其他的随机颜色吗?

这样的话, 需要去修改这个蓝色方块绘制时的画笔颜色, 相关代码片段:
https://github.com/ssthouse/organization-chart/blob/master/src/components/org-chart.js#L308

将这个method中的 `self.context.fillStyle = '#3ca0ff'` 换成你想要的随机色即可

**Comment by WangLei802** [comment]
您好 这边是需要把第二行每一个块的颜色都变得不一样

在 2019-03-05 14:10:20，"Shen Shuntian" <notifications@github.com> 写道：


是希望把蓝色换成其他的随机颜色吗?

这样的话, 需要去修改这个蓝色方块绘制时的画笔颜色, 相关代码片段:
https://github.com/ssthouse/organization-chart/blob/master/src/components/org-chart.js#L308

将这个method中的 self.context.fillStyle = '#3ca0ff' 换成你想要的随机色即可

**Comment by WangLei802** [comment]
你好这边是需要  第二行  每个块的颜色都不一样

**Comment by WangLei802** [comment]
> @ WangLei802 是希望把蓝色换成其他的随机颜色吗？
> 
> 这样的话，需要去修改这个蓝色方块绘制时的画笔颜色，相关代码片段：[https](https://github.com/ssthouse/organization-chart/blob/master/src/components/org-chart.js#L308)：
> [//github.com/ssthouse/organization-chart/blob/master/src/components/org-chart.js#L308](https://github.com/ssthouse/organization-chart/blob/master/src/components/org-chart.js#L308)
> 
> 将这个方法的中`self.context.fillStyle = '#3ca0ff'`换成你想要的随机色即可

你好这边是需要第二行每个块的颜色都不一样

**Comment by ssthouse** [comment]
> 你好这边是需要第二行每个块的颜色都不一样

要每个都不一样的话, 写一个函数用来随机生成颜色即可, 如:
```javascript
randomColor () {
    let letters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f']
    let color = '#'
    for (let i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)]
    }
    return color
  }
```

**Comment by WangLei802** [comment]
在 2019-03-05 14:46:29，"Shen Shuntian" <notifications@github.com> 写道：


你好这边是需要第二行每个块的颜色都不一样

要每个都不一样的话, 写一个函数用来随机生成颜色即可, 如:

randomColor () {

    let letters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f']

    let color ='#'for (let i =0; i <6; i++) {

      color += letters[Math.floor(Math.random() *16)]

    }

    return color

  }
